1Panel-dev/1Panel

- backend/app/dto/container.go
- backend/app/service/container.go
- backend/app/service/container_volume.go
- backend/constant/errs.go
- backend/i18n/lang/en.yaml
- backend/i18n/lang/zh.yaml
- frontend/src/api/interface/container.ts
- frontend/src/lang/modules/en.ts
- frontend/src/lang/modules/zh.ts
- frontend/src/views/container/compose/detail/index.vue
- frontend/src/views/container/container/index.vue
- frontend/src/views/container/image/index.vue
1. 删除存储卷增加使用中判断
2. 容器操作时增加来源判断
3. 解决删除镜像后页面没有自动刷新的问题
> fix: 容器部分已知问题修改

- frontend/package-lock.json
- frontend/src/components/container-log/index.vue
- frontend/src/views/container/container/log/index.vue
- frontend/src/views/database/mysql/setting/slow-log/index.vue
- frontend/src/views/host/terminal/host/operate/index.vue
> fix: 解决 mysql 慢日志设置修改失败的问题

- backend/app/service/container_network.go
- backend/app/service/container_volume.go
- backend/app/service/image.go
- backend/constant/errs.go
- backend/i18n/lang/en.yaml
- backend/i18n/lang/zh.yaml
- frontend/src/views/log/operation/index.vue
- frontend/src/views/setting/snapshot/index.vue
> fix: 容器删除使用中对象提示信息优化

- frontend/components.d.ts
- frontend/src/components/tooltip/index.vue
- frontend/src/views/container/compose/detail/index.vue
- frontend/src/views/container/compose/index.vue
- frontend/src/views/container/container/index.vue
- frontend/src/views/container/image/index.vue
- frontend/src/views/container/network/index.vue
- frontend/src/views/container/template/index.vue
- frontend/src/views/container/volume/index.vue
- frontend/src/views/cronjob/index.vue
- frontend/src/views/cronjob/record/index.vue
- frontend/src/views/website/website/index.vue
> fix: 表格可点击列超长样式优化

- frontend/src/lang/modules/en.ts
- frontend/src/lang/modules/zh.ts
- frontend/src/views/setting/panel/password/index.vue
> fix: 国际化换行问题修改

- backend/app/api/v1/backup.go
- backend/app/api/v1/cronjob.go
- backend/app/api/v1/file.go
- backend/app/repo/cronjob.go
- backend/app/service/cornjob.go
- backend/app/service/cronjob_helper.go
- backend/router/ro_file.go
- cmd/server/docs/docs.go
- cmd/server/docs/swagger.json
- cmd/server/docs/swagger.yaml
- frontend/src/api/modules/container.ts
- frontend/src/api/modules/cronjob.ts
- frontend/src/api/modules/files.ts
- frontend/src/api/modules/setting.ts
- frontend/src/components/backup/index.vue
- frontend/src/views/cronjob/record/index.vue
> fix: 解决计划任务备份文件失效仍能下载的问题

- backend/app/service/image.go
> Fix typo in image.go

- backend/app/api/v1/container.go
- backend/app/service/container.go
- backend/app/service/container_compose.go
- backend/utils/compose/compose.go
- frontend/src/api/modules/container.ts
- frontend/src/views/container/compose/create/index.vue
- frontend/src/views/container/image/build/index.vue
> fix:  创建编排改为异步操作

- backend/app/api/v1/container.go
- backend/app/service/container_compose.go
- backend/app/service/image.go
- backend/router/ro_container.go
- cmd/server/docs/docs.go
- cmd/server/docs/swagger.json
- cmd/server/docs/swagger.yaml
- frontend/src/api/modules/container.ts
- frontend/src/lang/modules/en.ts
- frontend/src/lang/modules/zh.ts
- frontend/src/views/container/compose/create/index.vue
- frontend/src/views/container/image/build/index.vue
fix: 修改镜像构建和编排创建路径限制，增加 config 校验
> fix: 修改镜像构建和编排创建路径限制，增加 config 校验

- backend/app/repo/app_install.go
- backend/app/service/app_install.go
> fix: 解决数据库密码修改未同步到应用的问题

- backend/app/service/snapshot.go
> fix: 解决快照同步恢复失败的问题

- README_EN.md
> docs: add README_EN.md.

- README.md
- README_EN.md
> Pr@dev@docs add readme en.md

- frontend/src/lang/modules/zh.ts
> chore: 简化社区软件协议文案

- frontend/src/views/login/index.vue
> fix: 登录页面优化适配

- frontend/src/views/login/index.vue
> fix: 修复登录页面从大屏切换小屏填写信息消失问题

- frontend/src/views/host/file-management/hooks/searchable.ts
- frontend/src/views/host/file-management/index.vue
文件支持地址栏直接访问
#539 #477 
https://user-images.githubusercontent.com/29268441/230732366-f1448c99-6d32-4b41-b5fb-93fbccd7f7f8.mp4
> feat: 文件支持输入URL直接访问

- frontend/components.d.ts
- frontend/src/views/website/website/config/basic/site-folder/index.vue
> style: 修改网站目录样式

- frontend/index.html
> fix: 为了安全，使面板首页禁止搜索引擎收录

- backend/app/api/v1/app.go
- cmd/server/docs/docs.go
- cmd/server/docs/swagger.json
- cmd/server/docs/swagger.yaml
> chore: fix some typos 
